# Generated by Django 6.0.2 on 2026-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
